"""kiwi

Revision ID: 7810fad48f9a
Revises: 7e3d47493cfc
Create Date: 2026-02-15 02:11:08.873469

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7810fad48f9a"
down_revision = "7e3d47493cfc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "kiwi_page",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("formatted_title", sa.String(length=255), nullable=False),
        sa.Column("raw_content", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_kiwi_page_id"), "kiwi_page", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_kiwi_page_id"), table_name="kiwi_page")
    op.drop_table("kiwi_page")
    # ### end Alembic commands ###
