"""Quick access

Revision ID: 7e3d47493cfc
Revises: 9bde093b0972
Create Date: 2026-02-12 23:54:56.009675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e3d47493cfc'
down_revision = '9bde093b0972'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quick_access_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('dname', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quick_access_link_id'), 'quick_access_link', ['id'], unique=False)
    op.create_index(op.f('ix_quick_access_link_url'), 'quick_access_link', ['url'], unique=True)
    op.create_table('quick_access_shortcut',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('shortcut', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['link_id'], ['quick_access_link.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quick_access_shortcut_id'), 'quick_access_shortcut', ['id'], unique=False)
    op.create_index(op.f('ix_quick_access_shortcut_shortcut'), 'quick_access_shortcut', ['shortcut'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quick_access_shortcut_shortcut'), table_name='quick_access_shortcut')
    op.drop_index(op.f('ix_quick_access_shortcut_id'), table_name='quick_access_shortcut')
    op.drop_table('quick_access_shortcut')
    op.drop_index(op.f('ix_quick_access_link_url'), table_name='quick_access_link')
    op.drop_index(op.f('ix_quick_access_link_id'), table_name='quick_access_link')
    op.drop_table('quick_access_link')
    # ### end Alembic commands ###
